apiVersion: v1
kind: Service
metadata:
  name: my-app-external-service
  namespace: alpha
spec:
  selector:
    app: nodejs-dob-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer